package com.sirweb.miro.lexer;

public enum TokenType {
    IDENT_TOKEN,
    FUNCTION_TOKEN,
    AT_KEYWORD_TOKEN,
    HASH_TOKEN,
    STRING_TOKEN,
    BAD_STRING_TOKEN,
    URL_TOKEN,
    BAD_URL_TOKEN,
    DELIM_TOKEN,
    NUMBER_TOKEN,
    PERCENTAGE_TOKEN,
    DIMENSION_TOKEN,
    UNICODE_RANGE_TOKEN,
    INCLUDE_MATCH_TOKEN,
    DASH_MATCH_TOKEN,
    PREFIX_MATCH_TOKEN,
    SUFFIX_MATCH_TOKEN,
    SUBSTRING_MATCH_TOKEN,
    COLUMN_TOKEN,
    WHITESPACE_TOKEN,
    NEWLINE_TOKEN,
    CDO_TOKEN,
    CDC_TOKEN,
    COLON_TOKEN,
    SEMICOLON_TOKEN,
    COMMA_TOKEN,
    O_Q_TOKEN,
    C_Q_TOKEN,
    O_R_TOKEN,
    C_R_TOKEN,
    O_C_TOKEN,
    C_C_TOKEN,
    COMMENT_TOKEN,

    MIRO_IDENT_TOKEN,
    EQUAL_TOKEN,

    ARITHMETIC_TOKEN,

    EQUAL_EQUAL_TOKEN,

    MIRO_INDENT_TOKEN,
    MIRO_DEDENT_TOKEN,
    MIRO_NESTPROP_TOKEN,
    MIRO_ARROW_TOKEN,
    MIRO_AND_TOKEN,
    MIRO_MIXIN_TOKEN,
    TILDE_TOKEN,
    MIRO_INTERPOLATION_TOKEN,
    MIRO_CONDITIONAL_TOKEN,
    MIRO_EXCLAMATION_TOKEN,

    MIRO_DEBUG_TOKEN,
    MIRO_DOT_TOKEN,
    EOF



}